stages:
  - test
  - build
  - deploy

default:
  image: ghcr.io/binkhq/python:3.9

test:complexity:
  stage: test
  before_script: &setup
    - pipenv install --dev --system --deploy --ignore-pipfile
    - pip freeze
  script:
    - xenon --no-assert --max-average A --max-modules B --max-absolute B .

test:style:
  stage: test
  before_script: *setup
  script:
    - flake8
    - black --line-length 120 --check .
    - isort --check --line-length 120 --profile black .

#type-check:
#  stage: tests
#  before_script: *setup
#  script:
#    - mypy --config-file .mypy.ini app tests

build:develop:
  stage: build
  needs: ["test:complexity", "test:style"]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - export CTAG=$(echo -n "$CI_PIPELINE_CREATED_AT" | sed s/\://g)
  script:
    - docker build --pull --tag "$CI_REGISTRY/$CI_PROJECT_NAME:$CTAG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME:$CTAG"
  only:
    - develop

deploy:dev:
  stage: deploy
  needs: ["build:develop"]
  image: binkcore.azurecr.io/tagbot:latest
  environment:
    name: dev
  before_script:
    - export CTAG=$(echo -n "$CI_PIPELINE_CREATED_AT" | sed s/\://g)
  script:
    - tagbot
      --username "$CI_REGISTRY_USER"
      --password "$CI_REGISTRY_PASSWORD"
      --source "$CI_REGISTRY/$CI_PROJECT_NAME:$CTAG"
      --tag "$CI_ENVIRONMENT_NAME-$CTAG"
    - tagbot
      --username "$CI_REGISTRY_USER"
      --password "$CI_REGISTRY_PASSWORD"
      --source "$CI_REGISTRY/$CI_PROJECT_NAME:$CTAG"
      --tag "$CI_ENVIRONMENT_NAME"
  only:
    - develop
