"""Email Template"""
EMAIL_TEMPLATE = "pytest_2.0_regression_email@bink.com"

""" Payment Cards Constant"""
FIRST_SIX_DIGITS = "first_six_digits"
LAST_FOUR_DIGITS = "last_four_digits"
TOKEN = "token"
NAME_ON_CARD = "name_on_card"
MONTH = "month"
YEAR = "year"
FINGERPRINT = "fingerprint"
HASH = "hash"
PAYMENT_CARD_STATUS = "status"
ACTIVE_LINK = "active_link"
PAYMENT_PROVIDER = "payment_provider"
PAYMENT_URL = "payment_url"
PAYMENT_ENCODING = "payment_encoding"
PAYMENT_DISCRIPTION = "payment_discription"
PAYMENT_VERIFICATION = "payment_verification"

"""Channel User Details"""
USER_ID = "uid"
PWD = "pwd"
